version: '3.8'

services:
  voice-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./output:/app/output
      - ./parler_models:/app/parler_models
      - ./models/whisper:/app/models/whisper
      - ./models/coqui:/app/models/coqui
      - ./models/huggingface:/app/models/huggingface
      - appuser-cache:/home/appuser/.cache
    environment:
      - LOG_LEVEL=INFO
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
      - REDIS_DB=0
      - RATE_LIMIT_TIER1=100
      - RATE_LIMIT_TIER2=1000
      - MAX_DAILY_COST=100.0
      - COST_TIER_RATIO=0.1
      - TTS_MODEL_ID=ai4bharat/indic-parler-tts
      - TTS_SAMPLING_RATE=16000
      - TTS_USE_CUDA=false
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY:-}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-eastus}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY:-}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-}
      - TRANSFORMERS_CACHE=/app/models/huggingface
      - TORCH_HOME=/app/models/coqui
      - HF_HOME=/app/models/huggingface
      - WHISPER_CACHE_DIR=/app/models/whisper
      - PARLER_CACHE_DIR=/app/parler_models
      - NUMBA_CACHE_DIR=/home/appuser/.cache/numba_cache
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispassword}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis-data:
  appuser-cache: {}
  whisper-cache:
  tts-cache: 